name: equatable_lint_example
description: Package with every examples for the equatable_lint_ultimate package
version: 0.1.2

publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  custom_lint: ^0.7.5
  equatable_lint_ultimate:
    path: ../
